Linux brew bug fix
trilogy-group/workspace-images pull request #10
Opened 2021-07-15 09:07 UTC by sri-vathsa

2021-07-15 11:50 UTC, pavan-tri requested changes

2021-07-15 11:50 UTC, pavan-tri commented on full/Dockerfile.arm64
> +  apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev && \
Can we add comments why this was done.
later in the file there is 2.6.6 ruby

2021-07-15 14:15 UTC, sri-vathsa commented on full/Dockerfile.arm64
> +  apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev && \
This is because brew needs ruby version 2.6.3 present to work as intended. Any version later than that is incompatible.  Ruby 2.6.6 installed later on in the file will be the default version of ruby and is managed by rvm. This installation step is not necessary for x86 as ruby has an official release of 2.6.3 for x86 and brew automatically takes care of that as a dependency for its working. Due to the unavailability of an official release for ARM we have to do this manually.

2021-07-18 11:30 UTC, pavan-tri approved these changes

2021-07-19 06:17 UTC, merged